# Project Name
TARGET = WaveBlender

# Sources
CPP_SOURCES += \
   CvMapping.cpp \
   OverlayCv.cpp \
   PageChannel.cpp \
   RandomWalkTables.cpp \
   CustomTable.cpp \
   WaveBlender.cpp

BASE_DIR = $(CURDIR)/../../../Base
include $(BASE_DIR)/MakefilePatch
