# Project Name
TARGET = Schaltzentrale

# Sources
CPP_SOURCES += \
    Main.cpp \
    PageAbstract.cpp \
    PageGate.cpp \
	 PageOverview.cpp \
    PageRamp.cpp

BASE_DIR = $(CURDIR)/../../../Base
include $(BASE_DIR)/MakefilePatch
